var all_trips = new Map([
  [ "1988Trip",          { "title" : "1988 Spring Break", "region" : "west" }],
  [ "1989Honeymoon",     { "title" : "1989 Honeymoon", "region" : "overseas" }],
  [ "1990Colorado",      { "title" : "1990 Spring Vacation", "region" : "rockies" }],
  [ "1990Trip",          { "title" : "1990 Autumn Vacation", "region" : "west" }],
  [ "1991Trip",          { "title" : "1991 Spring Vacation", "region" : "east" }],
  [ "1991FallFoliage",   { "title" : "1991 Autumn Vacation", "region" : "east" }],
  [ "1992Trip",          { "title" : "1992 Summer Vacation", "region" : "east" }],
  [ "1992OS2Trip",       { "title" : "1992 Business Trip", "region" : "west" }],
  [ "1992FallFoliage",   { "title" : "1992 Autumn Vacation", "region" : "east" }],
  [ "1993Trip",          { "title" : "1993 Spring Vacation", "region" : "west" }],
  [ "1993Homecoming",    { "title" : "1993 Autumn Vacation", "region" : "west" }],
  [ "1995Trip",          { "title" : "1995 Summer Vacation", "region" : "rockies" }],
  [ "1996-97RoseParade", { "title" : "1996-97 Winter Vacation", "region" : "west" }],
  [ "1998Colorado",      { "title" : "1998 Summer Vacation I", "region" : "rockies" }],
  [ "1998Trip",          { "title" : "1998 Summer Vacation II", "region" : "east" }],
  [ "1998Homecoming",    { "title" : "1998 Autumn Vacation", "region" : "west" }],
  [ "1999Trip",          { "title" : "1999 Autumn Vacation", "region" : "east" }],
  [ "2001Trip",          { "title" : "2001 Spring Vacation", "region" : "west" }],
  [ "2002Trip",          { "title" : "2002 Summer Vacation", "region" : "east" }],
  [ "2004Trip",          { "title" : "2004 Summer Vacation", "region" : "east" }],
  [ "2005Trip",          { "title" : "2005 Summer Vacation", "region" : "rockies" }],
  [ "2006Trip",          { "title" : "2006 Summer Vacation", "region" : "east" }],
  [ "2007Trip",          { "title" : "2007 Summer Vacation I", "region" : "west" }],
  [ "2007Colorado",      { "title" : "2007 Summer Vacation II", "region" : "rockies" }],
  [ "2008Trip",          { "title" : "2008 Summer Vacation", "region" : "east" }],
  [ "2009Trip",          { "title" : "2009 Summer Vacation", "region" : "rockies" }],
  [ "2010Trip",          { "title" : "2010 Summer Vacation I", "region" : "west" }],
  [ "2010Wisconsin",     { "title" : "2010 Summer Vacation II", "region" : "east" }],
  [ "2011Trip",          { "title" : "2011 Summer Vacation", "region" : "rockies" }],
  [ "2012Trip",          { "title" : "2012 Summer Vacation", "region" : "east" }],
  [ "2013Trip",          { "title" : "2013 Summer Vacation", "region" : "west" }],
  [ "2013-14Florida",    { "title" : "2013-14 Winter Break", "region" : "east" }],
  [ "2014WashDC",        { "title" : "2014 Spring Break", "region" : "east" }],
  [ "2014Trip",          { "title" : "2014 Summer Vacation", "region" : "rockies" }],
  [ "2014-15Arizona",    { "title" : "2014-15 Winter Break", "region" : "west" }],
  [ "2015Trip",          { "title" : "2015 Summer Vacation", "region" : "rockies" }],
  [ "2015NewMexico",     { "title" : "2015 Winter Break", "region" : "rockies" }],
  [ "2016WashDC",        { "title" : "2016 Spring Break", "region" : "east" }],
  [ "2016Alaska",        { "title" : "2016 Summer Vacation I", "region" : "west" }],
  [ "2016Trip",          { "title" : "2016 Summer Vacation II", "region" : "east" }],
  [ "2016Berlin",        { "title" : "2016 Business Trip", "region" : "overseas" }],
  [ "2017Dusseldorf",    { "title" : "2017 Business Trip", "region" : "overseas" }],
  [ "2017Trip",          { "title" : "2017 Summer Vacation", "region" : "rockies" }],
  [ "2018Dusseldorf",    { "title" : "2018 Business Trip", "region" : "overseas" }],
  [ "2018Colorado",      { "title" : "2018 Spring Break", "region" : "rockies" }],
  [ "2018Trip",          { "title" : "2018 Summer Vacation", "region" : "east" }],
  [ "2018-19Florida",    { "title" : "2018-19 Winter Break", "region" : "east" }],
  [ "2019Berlin",        { "title" : "2019 Business Trip I", "region" : "overseas" }],
  [ "2019Trip",          { "title" : "2019 Summer Vacation", "region" : "rockies" }],
  [ "2019Cologne",       { "title" : "2019 Business Trip II", "region" : "overseas" }],
  [ "2020Trip",          { "title" : "2020 Summer Vacation", "region" : "east" }],
  [ "2021Trip",          { "title" : "2021 Summer Vacation", "region" : "west" }],
  [ "2021Colorado",      { "title" : "2021 Autumn Vacation", "region" : "rockies" }],
  [ "2022Colorado",      { "title" : "2022 Spring Vacation", "region" : "rockies" }],
  [ "2022Trip",          { "title" : "2022 Summer Vacation", "region" : "east" }],
  [ "2023Trip",          { "title" : "2023 Summer Vacation", "region" : "rockies" }],
  [ "2023SanAntonio",    { "title" : "2023 Bowl Trip", "region" : "east" }],
  [ "2024LosAngeles",    { "title" : "2024 Concert Trip", "region" : "west" }],
  [ "2024-25Trip",       { "title" : "2024-25 Winter Break", "region" : "west" }],
]);
