var all_states = new Map([
  [ "AL", { "name" : "Alabama" }],
  [ "AK", { "name" : "Alaska" }],
  [ "AZ", { "name" : "Arizona" }],
  [ "AR", { "name" : "Arkansas" }],
  [ "CA", { "name" : "California" }],
  [ "CO", { "name" : "Colorado" }],
  [ "CT", { "name" : "Connecticut" }],
  [ "DC", { "name" : "District of Columbia" }],
//[ "DE", { "name" : "Delaware" }],
  [ "FL", { "name" : "Florida" }],
  [ "GA", { "name" : "Georgia" }],
//[ "HI", { "name" : "Hawaii" }],
  [ "ID", { "name" : "Idaho" }],
  [ "IL", { "name" : "Illinois" }],
  [ "IN", { "name" : "Indiana" }],
  [ "IA", { "name" : "Iowa" }],
  [ "KS", { "name" : "Kansas" }],
  [ "KY", { "name" : "Kentucky" }],
  [ "LA", { "name" : "Louisiana" }],
  [ "ME", { "name" : "Maine" }],
  [ "MD", { "name" : "Maryland" }],
  [ "MA", { "name" : "Massachusetts" }],
  [ "MI", { "name" : "Michigan" }],
  [ "MN", { "name" : "Minnesota" }],
  [ "MS", { "name" : "Mississippi" }],
  [ "MO", { "name" : "Missouri" }],
  [ "MT", { "name" : "Montana" }],
  [ "NE", { "name" : "Nebraska" }],
  [ "NV", { "name" : "Nevada" }],
  [ "NH", { "name" : "New Hampshire" }],
  [ "NJ", { "name" : "New Jersey" }],
  [ "NM", { "name" : "New Mexico" }],
  [ "NY", { "name" : "New York" }],
  [ "NC", { "name" : "North Carolina" }],
  [ "ND", { "name" : "North Dakota" }],
  [ "OH", { "name" : "Ohio" }],
  [ "OK", { "name" : "Oklahoma" }],
  [ "OR", { "name" : "Oregon" }],
  [ "PA", { "name" : "Pennsylvania" }],
  [ "RI", { "name" : "Rhode Island" }],
  [ "SC", { "name" : "South Carolina" }],
  [ "SD", { "name" : "South Dakota" }],
  [ "TN", { "name" : "Tennessee" }],
  [ "TX", { "name" : "Texas" }],
  [ "UT", { "name" : "Utah" }],
  [ "VT", { "name" : "Vermont" }],
  [ "VA", { "name" : "Virginia" }],
  [ "WA", { "name" : "Washington" }],
  [ "WI", { "name" : "Wisconsin" }],
//[ "WV", { "name" : "West Virginia" }],
  [ "WY", { "name" : "Wyoming" }],
]);

var all_states_canada = new Map([
  [ "AB", { "name" : "Alberta" }],
  [ "BC", { "name" : "British Columbia" }],
//[ "MB", { "name" : "Manitoba" }],
//[ "NB", { "name" : "New Brunswick" }],
//[ "NL", { "name" : "Newfoundland and Labrador" }],
//[ "NT", { "name" : "Northwest Territories" }],
//[ "NS", { "name" : "Nova Scotia" }],
//[ "NU", { "name" : "Nunavut" }],
  [ "ON", { "name" : "Ontario" }],
//[ "PE", { "name" : "Prince Edward Island" }],
  [ "QC", { "name" : "Quebec" }],
//[ "SK", { "name" : "Saskatchewan" }],
//[ "YT", { "name" : "Yukon" }],
]);

var all_states_other = new Map([
  [ "BRB", { "name" : "Barbados" }],
  [ "ENG", { "name" : "England" }],
  [ "DEU", { "name" : "Germany" }],
  [ "GRL", { "name" : "Greenland" }],
  [ "PRI", { "name" : "Puerto Rico" }],
  [ "SCT", { "name" : "Scotland" }],
]);
